<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\ProdutivAgro.SharedKernel\ProdutivAgro.SharedKernel.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Identity\Services\"/>
    </ItemGroup>

</Project>
