version: "3.8"

services:
  postgres:
    container_name: produtivagro-postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "@Password123"
      POSTGRES_DB: ProdutivAgroDb
