<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AutoMapper" Version="12.0.1"/>
        <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1"/>
        <PackageReference Include="FluentValidation" Version="12.1.1"/>
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1"/>
        <PackageReference Include="MediatR" Version="14.2.0"/>
        <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="11.1.0"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10"/>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Identity\Queries\"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ProdutivAgro.Domain\ProdutivAgro.Domain.csproj"/>
        <ProjectReference Include="..\ProdutivAgro.Exception\ProdutivAgro.Exception.csproj"/>
        <ProjectReference Include="..\ProdutivAgro.SharedKernel\ProdutivAgro.SharedKernel.csproj"/>
    </ItemGroup>

</Project>
